// packages/web/src/components/structure/Footer.tsx
import GitHub from '@mui/icons-material/GitHub'
import { Box, IconButton, SxProps, Theme, Typography } from '@mui/material'
import { ExternalLink } from '../atomics/atoms/ExternalLink'

export const Footer = () => {
  return (
    <Box component="footer" sx={sx}>
      <Typography variant="body2" component="span">
        © 2023 ishiyama0530
      </Typography>
      <IconButton>
        <ExternalLink href="https://github.com/ishiyama0530" target="_blank">
          <GitHub className="github-icon" />
        </ExternalLink>
      </IconButton>
    </Box>
  )
}

const sx: SxProps<Theme> = (t) => ({
  zIndex: t.zIndex.appBar,
  width: '100%',
  bgcolor: t.palette.background.default,
  position: 'fixed',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  bottom: 0,
  p: {
    xs: 1,
    sm: 3
  },
  '& .github-icon': {
    color: '#000'
  }
})

// packages/web.admin/src/components/structures/Footer.vue
<template>
  <footer>
    © 2023 ishiyama0530
    <ExternalLink href="https://github.com/ishiyama0530">
      <font-awesome-icon icon="fa-brands fa-github" class="github-icon" color="#000" />
    </ExternalLink>
  </footer>
</template>

<script lang="ts" setup>
import ExternalLink from '../elements/ExternalLink.vue'
</script>

<style scoped>
footer {
  z-index: 38;
  position: absolute;
  bottom: 0;
  padding: 20px;
  width: 100%;
  background-color: #fff;
  text-align: center;
}

.github-icon {
  font-size: 1.4em;
  margin-left: 6px;
}

@media screen and (max-width: 600px) {
  footer {
    padding: 14px;
  }
}
</style>
